# 数字日期和时间 

## 数字的四舍五入

In [3]:
print(round(1.23,1))
print(round(1.23456,3))
print(round(1627731,-1))
print(round(1627731,-4))

1.2
1.235
1627730
1630000


## 执行精确的浮点数运算

In [6]:
a = 4.2
b = 2.1
print(a + b)
print(a + b == 6.3)

from decimal import Decimal
a = Decimal('4.2')
b = Decimal('2.1')
print(a + b)
print(a + b == Decimal('6.3'))

6.300000000000001
False
6.3
True


In [9]:
from decimal import localcontext
a = Decimal('1.3')
b = Decimal('1.7')
print(a / b)
with localcontext() as ctx:
    ctx.prec = 3
    print(a / b)

0.7647058823529411764705882353
0.765


## 数字格式化输出

In [24]:
x = 1234.56789
print(format(x, '0.2f'))
print(format(x, '->10.1f'))
print(format(x, '-<10.1f'))
print(format(x, '-^10.1f'))
print(format(x,','))
print(format(x, ',.1f'))
print(format(x, 'e'))
print(format(x, '0.2E'))

1234.57
----1234.6
1234.6----
--1234.6--
1,234.56789
1,234.6
1.234568e+03
1.23E+03


##  二八十六进制整数

In [31]:
x = 1234
print(bin(x))
print(oct(x))
print(hex(x))
print('-'*20)
print(format(x, 'b'))
print(format(x, 'o'))
print(format(x, 'x'))
print('-'*20)
print(int('4d2',16))
print(int('10011010010', 2))

0b10011010010
0o2322
0x4d2
--------------------
10011010010
2322
4d2
--------------------
1234
1234


## 字节到大整数的打包与解包

In [40]:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'
print(len(data))
print(int.from_bytes(data, 'little'))
print(int.from_bytes(data, 'big'))
x = 94522842520747284487117727783387188
print(x.to_bytes(16, 'big'))
print(x.to_bytes(16, 'little'))

import struct
hi, lo = struct.unpack('>QQ', data)
print((hi << 64) + lo)

# 可以使用 int.bit_length() 方法来决定需要多少字节位来存储这个值。
x = 523 ** 23
print(x)
nbytes, rem = divmod(x.bit_length(), 8)
if rem:
    nbytes += 1
print(x.to_bytes(nbytes, 'little'))

16
69120565665751139577663547927094891008
94522842520747284487117727783387188
b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'
b'4\x00#\x00\x01\xef\xcd\x00\xab\x90x\x00V4\x12\x00'
94522842520747284487117727783387188
335381300113661875107536852714019056160355655333978849017944067
b'\x03X\xf1\x82iT\x96\xac\xc7c\x16\xf3\xb9\xcf\x18\xee\xec\x91\xd1\x98\xa2\xc8\xd9R\xb5\xd0'


## 复数的数学运算

In [48]:
a = complex(3, 4)
b = 3-5j
print(a, a.real, a.imag, a.conjugate())
print(b, b.real, b.imag, b.conjugate())
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(abs(a))

import cmath
print(cmath.sin(a))
print(cmath.cos(a))
print(cmath.exp(a))

(3+4j) 3.0 4.0 (3-4j)
(3-5j) 3.0 -5.0 (3+5j)
(6-1j)
9j
(29-3j)
(-0.3235294117647059+0.7941176470588236j)
5.0
(3.853738037919377-27.016813258003936j)
(-27.034945603074224-3.8511533348117775j)
(-13.128783081462158-15.200784463067954j)


## 无穷大与 NaN

In [51]:
inf = float('inf')
neg_inf = float('-inf')
NaN = float('nan')
print(inf, neg_inf, NaN)
import math
print(math.isinf(inf))
print(math.isinf(neg_inf))
print(math.isnan(NaN))

inf -inf nan
True
True
True


## 分数运算

In [6]:
from fractions import Fraction

a = Fraction(5, 4)
b = Fraction(7, 16)

print(a + b)
print(a * b)

c = a * b
print(c.numerator, c.denominator)

print(float(c))

print(c.limit_denominator(8))

x = 3.75
y = Fraction(*x.as_integer_ratio())
print(y)

27/16
35/64
35 64
0.546875
4/7
15/4


## 大型数组运算

In [13]:
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
print(x * 2)
print(x + y)

import numpy as np
ax = np.array([1, 2, 3, 4])
ay = np.array([5, 6, 7, 8])
print(ax * 2)
print(ax + ay)

def f(x):
    return x**2

print(f(ax))
print(np.sqrt(ax)) # numpy内置的通用函数（如sqrt）比math模块中的块
print(np.cos(ax))

[1, 2, 3, 4, 1, 2, 3, 4]
[1, 2, 3, 4, 5, 6, 7, 8]
[2 4 6 8]
[ 6  8 10 12]
[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


## 矩阵与线性代数运算

In [24]:
import numpy as np

m = np.matrix([[1,-2,3],[0,4,5],[7,8,-9]])
print(m)
print(m.T)
print(m.I)
v = np.matrix([[2],[3],[4]])
print(m * v)

import numpy.linalg

print(numpy.linalg.det(m))
print(numpy.linalg.eigvals(m))
print(numpy.linalg.solve(m, v))

[[ 1 -2  3]
 [ 0  4  5]
 [ 7  8 -9]]
[[ 1  0  7]
 [-2  4  8]
 [ 3  5 -9]]
[[ 0.33043478 -0.02608696  0.09565217]
 [-0.15217391  0.13043478  0.02173913]
 [ 0.12173913  0.09565217 -0.0173913 ]]
[[ 8]
 [32]
 [ 2]]
-229.99999999999983
[-13.11474312   2.75956154   6.35518158]
[[0.96521739]
 [0.17391304]
 [0.46086957]]


## 随机选择

In [82]:
import random

values = [1, 2, 3, 4, 5, 6]
# 随机选择一个
print(random.choice(values))
# 随机选择n个
print(random.sample(values, 3))
# 打乱
random.shuffle(values)
print(values)
# 生成随机整数
print(random.randint(1,10))
# 生成0-1随机浮点数
print(random.random())
# 生成N位随机位（二进制）的整数
print(random.getrandbits(200))

3
[6, 4, 3]
[5, 2, 1, 3, 4, 6]
7
0.8051427420789375
709720960601894187371878292665270967221516886150453990958172


## 基本的日期与时间转换

In [87]:
from datetime import timedelta
a = timedelta(days=2, hours=6)
b = timedelta(hours=4.5)
c = a + b
print(c.days)
print(c.seconds)

from datetime import datetime
a = datetime(2020, 6, 23)
print(a + timedelta(days=7))
b = datetime(2020, 6, 30)
print((b - a).days)

2
37800
2020-06-30 00:00:00
7


## 计算最后一个周五的日期

In [89]:
from datetime import datetime, timedelta

weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday','Friday', 'Saturday', 'Sunday']

def get_previous_byday(dayname, start_date = None):
    if start_date is None:
        start_date = datetime.today()
    day_num = start_date.weekday()
    day_num_target = weekdays.index(dayname)
    days_ago = (7 + day_num - day_num_target) % 7
    if days_ago == 0:
        days_ago = 7
    target_date = start_date - timedelta(days=days_ago)
    return target_date

print(get_previous_byday('Monday'))
# 执行大量的日期计算的话，最好安装第三方包 python-dateutil

2020-06-22 17:28:49.412610


## 计算当前月份的日期范围

In [2]:
from datetime import datetime, date, timedelta
import calendar
def get_month_range(start_date=None):
    if start_date is None:
        start_date = date.today().replace(day=1)
    _, days_in_month = calendar.monthrange(start_date.year, start_date.month)
    end_date = start_date + timedelta(days=days_in_month)
    return (start_date, end_date)

a_day = timedelta(days=1)
first_day, last_day = get_month_range()
while first_day < last_day:
    print(first_day)
    first_day += a_day

2020-06-01
2020-06-02
2020-06-03
2020-06-04
2020-06-05
2020-06-06
2020-06-07
2020-06-08
2020-06-09
2020-06-10
2020-06-11
2020-06-12
2020-06-13
2020-06-14
2020-06-15
2020-06-16
2020-06-17
2020-06-18
2020-06-19
2020-06-20
2020-06-21
2020-06-22
2020-06-23
2020-06-24
2020-06-25
2020-06-26
2020-06-27
2020-06-28
2020-06-29
2020-06-30


## 字符串转换为日期

In [3]:
from datetime import datetime
text = '2020-06-23'
y = datetime.strptime(text, '%Y-%m-%d')
z = datetime.now()
print(z-y)

# strptime() 性能很差，因为它是使用纯 Python 实现，并且必须处理所有的系统本地设置。

from datetime import datetime
def parse_ymd(s):
    year_s, mon_s, day_s = s.split('-')
    return datetime(int(year_s), int(mon_s), int(day_s))
# 实际测试中，这个函数比 datetime.strptime() 快 7 倍多。

17:41:44.383312
